name: Release
env:
  MACOSX_DEPLOYMENT_TARGET: '10.14'
on:
  release:
    types: [published]
jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: CMake
        run: |
          cmake -B build .
          cmake build
      - name: Build
        run: |
          cd build
          msbuild jsfuck.sln -noLogo -p:Configuration=Release
          move .\Release\*.lib ..
          move .\Release\*.dll ..
          move .\Release\*.exe ..
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: jsfuck-windows
          path: |
            *.exe
            *.lib
            *.dll
  build-macos:
    name: Build for macOS 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: CMake
        run: |
          cmake -B build .
          cmake build
      - name: Build
        run: |
          cd build
          make
          mv *.a ..
          mv *.dylib ..
          mv jsfuck ..
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: jsfuck-macos
          path: |
            jsfuck
            *.a
            *.dylib
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CMake
        run: |
          cmake -B build .
          cmake build
      - name: Build
        run: |
          cd build
          make
          mv *.a ..
          mv *.so ..
          mv jsfuck ..
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: jsfuck-linux
          path: |
            *.a
            *.so
            jsfuck
  publish:
    needs:
      - build-windows
      - build-macos
      - build-linux
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Zipping all artifacts
        run: |
          cd artifacts
          for i in */; do zip -0 -r "${i%/}.zip" "$i" & done; wait
          mv *.zip ..
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./jsfuck-windows.zip
          asset_name: jsfuck-windows.zip
          asset_content_type: application/zip
      - name: Upload macOS artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./jsfuck-macos.zip
          asset_name: jsfuck-macos.zip
          asset_content_type: application/zip
      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./jsfuck-linux.zip
          asset_name: jsfuck-linux.zip
          asset_content_type: application/zip
      - name: Upload include file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./include/jsfuck.h
          asset_name: jsfuck.h
          asset_content_type: text/plain