name: Test
env:
  MACOSX_DEPLOYMENT_TARGET: '10.14'
'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '.github/**'
  pull_request: null
jobs:
  build-msvc:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: CMake
        run: |
          cmake -B build .
          cmake build
      - name: Build
        run: |
          msbuild build/jsfuck.sln -noLogo
  build-macos:
    name: Build for MacOS 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: CMake
        run: |
          cmake -B build .
          cmake build
      - name: Build
        run: |
          cd build
          make
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CMake
        run: |
          cmake -B build .
          cmake build
      - name: Build
        run: |
          cd build
          make